#!/bin/bash
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -eu

title()
{
    printf "\n"
    echo "$@"
    n=77
    for i in $(seq $n)
    do
        printf "%s" -
    done
    printf '\n'
}


run_yarns()
{
    yarn yarns/*.yarn \
         -s yarns/lib.py --shell python2 --shell-arg '' --cd-datadir "$@"
}

title "Unit tests"
python3 -m CoverageTestRunner --ignore-missing-from=without-tests qvarn qvarnutils

title "Code style"
pycodestyle qvarn qvarnutils qvarn-copy qvarn-dump qvarn-stats

title "Pylint3"
pylint3 -j0 --rcfile pylint.conf qvarn qvarnutils qvarn-copy qvarn-dump qvarn-stats

title "Yarns"
if [ "${QVARN_POSTGRES:-no}" = no ]
then
    # Run yarns without Postgres. For speed.
   run_yarns "$@"
else
    scripts/pgempty
    run_yarns --env "QVARN_POSTGRES=$QVARN_POSTGRES" "$@"
fi
