#!/bin/bash
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -eu

run_yarns()
{
    yarn yarns/*.yarn \
         -s yarns/lib.py --shell python2 --shell-arg '' --cd-datadir "$@"
}

python3 -m CoverageTestRunner --ignore-missing-from=without-tests

pep8 qvarn
pylint3 -j0 --rcfile pylint.conf qvarn

if [ "${QVARN_POSTGRES:-no}" = no ]
then
    # Run yarns without Postgres. For speed.
   run_yarns "$@"
else
    scripts/pgempty
    run_yarns --env "QVARN_POSTGRES=$QVARN_POSTGRES" "$@"
fi
