#!/usr/bin/python3
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
import time

import Crypto.PublicKey.RSA

import apifw


filename = sys.argv[1]
iss = sys.argv[2]
sub = sys.argv[3]
aud = sys.argv[4]
scopes = ' '.join(sys.argv[5].split())

key_text = open(filename, 'r').read()
key = Crypto.PublicKey.RSA.importKey(key_text)

now = time.time()
claims = {
    'iss': iss,
    'sub': sub,
    'aud': aud,
    'exp': now + 3600,
    'scope': scopes,
}

token = apifw.create_token(claims, key)
sys.stdout.write(token.decode('ascii'))
