#!/usr/bin/python3
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys

import Crypto.PublicKey.RSA


RSA_KEY_BITS = 4096  # A nice, currently safe length

key = Crypto.PublicKey.RSA.generate(RSA_KEY_BITS)

filename = sys.argv[1]

def write(filename, byts):
    with open(filename, 'w') as f:
        f.write(byts.decode('ascii'))

write(filename, key.exportKey('PEM'))
write(filename + '.pub', key.exportKey('OpenSSH'))
