#!/bin/sh
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu


log="$1"
token="$2"


tmp="$(mktemp -d)"

cleanup()
{
    rm -rf "$tmp"
}

trap cleanup EXIT

export APITEST_ISS=testissuer
export APITEST_AUD=aud
export APITEST_LOG="$log"

./generate-rsa-key "$tmp/key"
./create-token "$tmp/key" "$APITEST_ISS" "$APITEST_AUD" uapi_version_get > "$token"
export APITEST_PUBKEY="$(cat "$tmp/key.pub")"

gunicorn --bind 127.0.0.1:12765 -p "$tmp/pid" -w16 \
         --log-file "$log" --log-level=debug apitest:app
