#!/bin/sh
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu


token="$1"


tmp="$(mktemp -d)"

cleanup()
{
    rm -rf "$tmp"
}

trap cleanup EXIT

scopes="
uapi_subjects_get
uapi_subjects_id_get
uapi_subjects_post
uapi_version_get
"

ISS=test
AUD=aud
./generate-rsa-key "$tmp/key"
./create-token "$tmp/key" "$ISS" "$AUD" "$scopes" > "$token"

cat <<EOF > "$tmp/qvarn.yaml"
log: 
  - filename: qvarn.log
token-issuer: $ISS
token-audience: $AUD
token-public-key: $(cat "$tmp/key.pub")
EOF
export QVARN_CONFIG="$tmp/qvarn.yaml"

gunicorn3 --bind 127.0.0.1:12765 -p "$tmp/pid" -w1 qvarnbackend:app
