#!/bin/sh
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu


token="$1"


tmp="$(mktemp -d)"

cleanup()
{
    rm -rf "$tmp"
}

trap cleanup EXIT

scopes="
uapi_persons_get
uapi_persons_id_get
uapi_persons_post
uapi_subjects_get
uapi_subjects_id_get
uapi_subjects_post
uapi_version_get

uapi_files_post
uapi_files_get
uapi_files_id_get
uapi_files_search_id_get
uapi_files_id_put
uapi_files_id_delete
uapi_files_id_file_get
uapi_files_id_file_put
uapi_jobs_post
uapi_jobs_get
uapi_jobs_id_get
uapi_jobs_search_id_get
uapi_jobs_id_put
uapi_jobs_id_delete
uapi_contracts_post
uapi_contracts_get
uapi_contracts_id_get
uapi_contracts_search_id_get
uapi_contracts_id_put
uapi_contracts_id_delete
uapi_contracts_id_document_get
uapi_contracts_id_document_put
uapi_persons_post
uapi_persons_get
uapi_persons_id_get
uapi_persons_search_id_get
uapi_persons_id_put
uapi_persons_id_delete
uapi_persons_id_private_get
uapi_persons_id_private_put
uapi_persons_id_photo_get
uapi_persons_id_photo_put
uapi_report_accesses_post
uapi_report_accesses_get
uapi_report_accesses_id_get
uapi_report_accesses_search_id_get
uapi_report_accesses_id_put
uapi_report_accesses_id_delete
uapi_report_accesses_id_pdf_get
uapi_report_accesses_id_pdf_put
uapi_data_cache_post
uapi_data_cache_get
uapi_data_cache_id_get
uapi_data_cache_search_id_get
uapi_data_cache_id_put
uapi_data_cache_id_delete
uapi_projects_post
uapi_projects_get
uapi_projects_id_get
uapi_projects_search_id_get
uapi_projects_id_put
uapi_projects_id_delete
uapi_competence_types_post
uapi_competence_types_get
uapi_competence_types_id_get
uapi_competence_types_search_id_get
uapi_competence_types_id_put
uapi_competence_types_id_delete
uapi_competence_types_id_card_front_get
uapi_competence_types_id_card_front_put
uapi_competence_types_id_card_back_get
uapi_competence_types_id_card_back_put
uapi_competence_types_id_registry_logo_get
uapi_competence_types_id_registry_logo_put
uapi_reports_post
uapi_reports_get
uapi_reports_id_get
uapi_reports_search_id_get
uapi_reports_id_put
uapi_reports_id_delete
uapi_reports_id_pdf_get
uapi_reports_id_pdf_put
uapi_competences_post
uapi_competences_get
uapi_competences_id_get
uapi_competences_search_id_get
uapi_competences_id_put
uapi_competences_id_delete
uapi_version_post
uapi_version_get
uapi_version_id_get
uapi_version_search_id_get
uapi_version_id_put
uapi_version_id_delete
uapi_bolagsfakta_suppliers_post
uapi_bolagsfakta_suppliers_get
uapi_bolagsfakta_suppliers_id_get
uapi_bolagsfakta_suppliers_search_id_get
uapi_bolagsfakta_suppliers_id_put
uapi_bolagsfakta_suppliers_id_delete
uapi_cards_post
uapi_cards_get
uapi_cards_id_get
uapi_cards_search_id_get
uapi_cards_id_put
uapi_cards_id_delete
uapi_cards_id_holder_photo_get
uapi_cards_id_holder_photo_put
uapi_cards_id_issuer_logo_get
uapi_cards_id_issuer_logo_put
uapi_orgs_post
uapi_orgs_get
uapi_orgs_id_get
uapi_orgs_search_id_get
uapi_orgs_id_put
uapi_orgs_id_delete

"

ISS=test
AUD=aud
./generate-rsa-key "$tmp/key"
./create-token "$tmp/key" "$ISS" "$AUD" "$scopes" > "$token"

cat <<EOF > "$tmp/qvarn.yaml"
baseurl: http://localhost:12765
log: 
  - filename: qvarn.log
token-issuer: $ISS
token-audience: $AUD
token-public-key: $(cat "$tmp/key.pub")
resource-type-dir: resource_type
memory-database: no
database:
  host: localhost
  port: 5432
  database: qvarn
  user: qvarn
  password: pass
  min_conn: 1
  max_conn: 1
EOF
export QVARN_CONFIG="$tmp/qvarn.yaml"

gunicorn3 --bind 127.0.0.1:12765 -p "$tmp/pid" -w1 --log-file g.log \
          --log-level debug \
          qvarnbackend:app
