#!/bin/sh
# Copyright (C) 2017  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

export QVARN_CONFIG="/etc/qvarn/qvarn.conf"

gunicorn3 \
    --bind 0.0.0.0:12765 \
    -w1 \
    --log-file /var/log/qvarn/gunicorn3.log \
    --log-level debug \
    qvarn.backend:app
